### ISSUE TITLE
Famicom Disk System? 

### ISSUE THREAD

**Issue by TronVonDoom** [Duimon/Retroarch-Overlays#5]
Hello! I really appreciate your work and have configured my arcade machine with all of your images. I see that they have a Famicom image, but can you do a Famicom Disk System image? Image for reference. 

![fds](https://user-images.githubusercontent.com/41256968/210125668-23ad22a3-57aa-4076-bff2-f2274002166e.png)

**Comment by Duimon** [comment]
I have a new list on my libretro page. (Link in the readme.) It is on the list but I have other maintenance task to do before I do any more graphics.
