### ISSUE TITLE
Source for the "no curvature" overlays?

### ISSUE THREAD

**Issue by wn2000** [Duimon/Retroarch-Overlays#6]
I like the "no curvature" overlays a lot.
Any chance you could upload the a .psd template?
Thanks!

**Comment by Duimon** [comment]
The no-curve are just my regular overlays with a hole cut in the middle and a drop shadow added. If you can make use of a PSD file, you really don't need one.

While I have a source repo for my overlays, it is very outdated. To be honest I will probably remove it. All my current overlays are generated using tools in the Mega Bezel. (Aside from a simple drop shadow for the screen inner shadow.)

I will probably add the "style" for the shadow to my Front-End-Assets repo.

You can check the guides folder in my Duimon-Mega-Bezel repo... there will eventually be a guide on how use the masking tools built into the Mega Bezel to generate overlays.
